all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_common_args: "-J ubuntu@158.160.113.82"

  children:
    webservers:
      hosts:
        web-a:
          ansible_host: 192.168.20.19
        web-b:
          ansible_host: 192.168.30.6

    monitoring:
      hosts:
        prometheus:
          ansible_host: 192.168.20.30
        grafana:
          ansible_host: 178.154.200.203

    logs:
      hosts:
        elasticsearch:
          ansible_host: 192.168.20.3
        kibana:
          ansible_host: 89.169.130.108
